# golangci-lint configuration for gristle
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  go: "1.24"

linters:
  disable-all: true
  enable:
    - errcheck      # Check for unchecked errors
    - gosec         # Security checks
    - staticcheck   # Static analysis
    - gocritic      # Opinionated linter
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code duplication detection
    - ineffassign   # Detect ineffective assignments
    - unconvert     # Remove unnecessary type conversions
    - govet         # Go vet checks
    - nilnil        # Check for nil,nil returns
    - revive        # Fast, configurable linter

linters-settings:
  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude-functions:
      - fmt.Print
      - fmt.Println
      - fmt.Printf
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - encoding/json.Unmarshal
      - (*encoding/json.Decoder).Decode

  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - commentedOutCode
      - ifElseChain
      - elseif
      - sprintfQuotedString

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      # Disabled for now: too many existing violations
      # - name: exported
      - name: if-return
      # - name: increment-decrement
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      # - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  staticcheck:
    checks:
      - all

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Test files have relaxed rules
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - errcheck

    # Main entry point often has higher complexity
    - path: main\.go
      linters:
        - gocyclo

    # TUI has inherently high complexity due to Bubble Tea event handling
    - path: tui/tui\.go
      linters:
        - gocyclo

  exclude-use-default: false
  fix: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
